version: '3.7'

services:
  devphio_payment_gateway_api:
    container_name: devphio_payment_gateway_api_dev
    build:
      context: ../../
      dockerfile: docker/dev/dev.dockerfile
    volumes:
      - '../../:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    env_file: 
      - ../../.env
    environment:
      - APP_HOST=devphio_payment_gateway_api
      - TYPEORM_HOST=devphio_payment_gateway_db
    depends_on:
      - devphio_payment_gateway_db
      - devphio_payment_gateway_redis
    command: sh -c "docker/service-checker.sh && yarn start:dev"

  devphio_payment_gateway_db:
    container_name: devphio_payment_gateway_db
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=devph_io_admin
      - POSTGRES_PASSWORD=DEVPHIO_supersecret
      - POSTGRES_DB=payment-gateway
  
  devphio_payment_gateway_redis:
    container_name: devphio_payment_gateway_redis
    image: redis:6.0-alpine
    restart: always
    command: redis-server --requirepass DEVPHIO_supersecret
    ports:
      - 6379:6379

volumes:
  postgres_data: