version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=payment-gateway

volumes:
  postgres_data: