# This is a basic workflow to help you get started with Actions

name: Sanitize BE and FE

# Trigger jobs on...
on: [push, pull_request]

jobs:
  test_FE:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies and trigger basic checkers for ADMIN PAGE
      run: |
        cd ./backend/admin
        npm install
        npm run lint
        npm run test
    - name: Install dependencies and trigger basic checkers for CLIENT PAGE
      run: |
        cd ./frontend/client
        npm install
        npm run lint
        npm run test
  
  # NOTE: 
  # - psql and yarn are already included in ubuntu-latest
  # - ref: https://github.com/mirromutth/mysql-action/issues/2#issuecomment-537763992
  test_BE:
    runs-on: ubuntu-latest
    services:
      devphio_payment_gateway_db:
        image: postgres
        env:
          POSTGRES_USER: devph_io_admin
          POSTGRES_PASSWORD: DEVPHIO_supersecret
          POSTGRES_DB: payment-gateway
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies and trigger basic checkers for API
      env:
        TYPEORM_HOST: devphio_payment_gateway_db
      run: |
        cd ./api
        env
        ./docker/service-checker.sh
